services:
  - type: web
    name: kyb-automation-api
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node kyb.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: COMPANY_HOUSE_API_KEY
        sync: false
      - key: PORT
        value: 3000 